[2024-06-05T03:38:25.198+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T03:38:25.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load manual__2024-06-05T03:37:58.706613+00:00 [queued]>
[2024-06-05T03:38:25.236+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load manual__2024-06-05T03:37:58.706613+00:00 [queued]>
[2024-06-05T03:38:25.237+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T03:38:25.253+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-06-05 03:37:58.706613+00:00
[2024-06-05T03:38:25.274+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=541) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-05T03:38:25.275+0000] {standard_task_runner.py:63} INFO - Started process 543 to run task
[2024-06-05T03:38:25.273+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load', 'manual__2024-06-05T03:37:58.706613+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpawjpfdlt']
[2024-06-05T03:38:25.276+0000] {standard_task_runner.py:91} INFO - Job 321: Subtask load
[2024-06-05T03:38:25.291+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-05T03:38:25.329+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.load manual__2024-06-05T03:37:58.706613+00:00 [running]> on host aa989158b36e
[2024-06-05T03:38:25.417+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T03:37:58.706613+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T03:37:58.706613+00:00'
[2024-06-05T03:38:25.418+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T03:38:25.452+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/google/cloud/firestore_v1/base_collection.py:302 UserWarning: Detected filter using positional arguments. Prefer using the 'filter' keyword argument instead.
[2024-06-05T03:38:31.607+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T03:38:31.607+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T03:38:31.618+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load, run_id=manual__2024-06-05T03:37:58.706613+00:00, execution_date=20240605T033758, start_date=20240605T033825, end_date=20240605T033831
[2024-06-05T03:38:31.645+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T03:38:31.669+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T03:38:31.678+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
